#ifndef WEX_DATA_CONSTRAINTS_H_INCLUDED
#define WEX_DATA_CONSTRAINTS_H_INCLUDED

//define some data cnostraints here

#define MAX_SHORT_STRING_LENGTH 128

#define NETWORK_BUFF_SIZE 1024

#define MAX_METHODNAME_LENGTH 32

#define MAX_PRONAME_LENGTH 32

#define MAX_VERSIONONAME_LENGTH 32

#define MAX_CODE_LENGTH 16

#define ORIGINAL_CONTENT_LENGTH 1024

#define MAX_HEADER_LENGTH 256

#endif // WEX_DATA_CONSTRAINTS_H_INCLUDED
